### ISSUE TITLE
Navigation bar positon wrong

### ISSUE THREAD

**Issue by indevizible** [inamiy/YIFullScreenScroll#15]
![screen shot 2013-06-28 at 1 28 38 pm](https://f.cloud.github.com/assets/1861329/720384/69a5ce7e-dfbc-11e2-8f82-a42d77441dc1.png)

ps. i receive self.view.frame = {{0, 20}, {320, 548}}

**Comment by inamiy** [comment]
Hmm, haven't seen this before.
Maybe you have set `-setStatusBarHidden:withAnimation:` before pushing to this viewController,
so changing its timing might help solving this issue.

It'll alos be helpful if you can send me a demo for this.

**Comment by indevizible** [comment]
hi @inamiy this is my demo project https://bitbucket.org/infostant/dmconnexdemo then open my xcworkspace file.

Thanks for your help

**Comment by inamiy** [comment]
Thanks for demo.
It seems fullScreenScroll is working well if you don't use `MMDrawerController` as a container.
(I tested it by commenting-out line 51-65, just to present center view-controller only)

I guess `MMDrawerController` is not fully compatible with modal presentation.
Since MMDrawerController should be the rootViewController of your app (not as modal for short period of time),
I recommend you change your code to not calling `-presentViewController:animated:completion:`.

If you have tried the above but still doesn't solve the issue,
then there may fundamentally exist `MMDrawerController` tweaking UIKit's normal layouting behavior,
so please let me know because I also like `MMDrawerController` :)

**Comment by indevizible** [comment]
I've try to set <code>MMDrawerController</code> to root view and it's not solve my problem too
I notice when present other <code>UIViewController</code> i got frame position (0,0)
but <code>MMDrawerViewController</code> i got (0,20) and  20 is height of status bar 
then I try to change <code>#define STATUS_BAR_HEIGHT </code> in <code>YIFullScreenScroll.m</code> to 0 , its work fine for <code>MMDrawerController</code> but not for another 

Can I have a right way to redefine this define or set this gap without edit this file because I use pod to update my project

**Comment by inamiy** [comment]
OK, now I fixed the issue.
Please try this in your Podfile.
I tested directly in `MMDrawerController`'s demo app, so it should work :)

```
pod 'YIFullScreenScroll', :git => 'https://github.com/inamiy/YIFullScreenScroll', :commit => '7f5b0765e59ebd635bf0ee9e00745457fc070bcc'
```

**Comment by indevizible** [comment]
Thank you ,@inamiy . My app can run perfectly by your code :)  :+1:
