### ISSUE TITLE
Not respecting bottomLayoutGuide When Resizing

### ISSUE THREAD

**Issue by eni9889** [inamiy/YIFullScreenScroll#28]
I have a UIWebView that is set to be 1 pixel above the bottomLayoutGuide which is where the top of the tabbar should be and when the tabbar hides the webview should expand but it does not.

"A view controller within a container view controller does not set this property’s value. Instead, the container view controller constrains the value to indicate the top of the tab bar or toolbar, if one of these is visible, or else to indicate the bottom edge of the view controller’s view."

**Comment by inamiy** [comment]
Sorry, this library is not intended for use with `UIScrollView` that doesn't have full width & height to the screen, since adjusting its frame during scroll can be a performance-critical issue. 

This means, `bottomLayoutGuide` always needs to be 0 for usage.

In your case, please set your `UIWebView` at fullscreen size and let `YIFullScreenScroll` adjust only UITabBar. I guess this will be sufficient for most of the time.

**Comment by inamiy** [comment]
This issue will be closed as mentioned above.
