### ISSUE TITLE
Unable to activate UINavigationBar drop shadow

### ISSUE THREAD

**Issue by ghost** [inamiy/YIFullScreenScroll#4]
Maybe you can tell me how :) or did you disable it?

**Comment by inamiy** [comment]
This issue is interesting because
I tried Xcode's Master-Detail Application Project Template as a test 
and found that it also has disabled navigationBar's drop-shadow!

I also tried 'UINavigationController -> UIViewController' structure from scratch,
but this time it properly adds drop-shadow.

So, I don't really know what is the condition of iOS6 adding drop-shadow,
but I guess my library is just conforming to this strange behavior,
and I'm afraid to say, this is the right spec :-(

**Comment by ghost** [comment]
I already tried to use [UINavigationBar appearance] to set the shadow, but nothing happens.

**Comment by inamiy** [comment]
Can you reproduce bug in demo project for this issue as well?

**Comment by inamiy** [comment]
Can't reproduce the issue so far, so I will close here.
